### ISSUE TITLE
Next build? 

### ISSUE THREAD

**Issue by tnfAngel** [JSPaste/Library#8]
No acabo de entender el sentido que tiene

**Comment by inetol** [comment]
Si te refieres a los scripts, seguramente se me olvido de retirarlo cuando sincronizaba los cambios del frontend a la libreria :P

Puedes retirarlo, todavia el sistema de build no esta hecho.

**Comment by tnfAngel** [comment]
> Si te refieres a los scripts, seguramente se me olvido de retirarlo cuando sincronizaba los cambios del frontend a la libreria :P
> 
> Puedes retirarlo, todavia el sistema de build no esta hecho.

Ah vale JAJAJAJA, estaba flipando
